### ISSUE TITLE
Make warns to expect errors when disabling optional modules

### ISSUE THREAD

**Issue by SemjonKerner** [RIOT-OS/RIOT#10047]
When testing  #10005 I got a warning from Make to **EXPECT ERRORS!** when compiling with `DISABLE_MODULE=periph_gpio_irq`.
This warning is needless since the feature `periph_gpio_irq` is optional and thus excluding it should not throw any errors. Even more, if it throws errors then there is a bug that should neither be expected nor in the code at all.

Meaning if a feature added with `FEATURES_OPTIONAL` is excluded again with `DISABLE_MODULE`, this warning should not be printed.

**Comment by cladmi** [comment]
The `DISABLE_MODULE` should only disable `DEFAULT_MODULES` according to the documentation: https://github.com/RIOT-OS/RIOT/blob/8e9c28dac3fbbf7aede23d5078f29d722e9daf7f/makefiles/vars.inc.mk#L18

Later, a warning was introduced by https://github.com/RIOT-OS/RIOT/pull/1734 which, against the documentation, stated that `DISABLE_MODULE` could disable any module.

And then, later, in conformity to the warning but still against the documentation, the module was indeed removed by https://github.com/RIOT-OS/RIOT/pull/2951 (for a PR that I think at the end did not use it as it change to use the 'default_' module name pattern https://github.com/RIOT-OS/RIOT/pull/2947#issuecomment-101750001)

For me the BUG is that this variable removes the module. It is even problematic currently as `USEMODULES` is modified after

----

Also, `PERIPH_OPTIONAL` is defined as 'include the feature if provided', not you may not use it even if it is available.
https://github.com/RIOT-OS/RIOT/blob/8e9c28dac3fbbf7aede23d5078f29d722e9daf7f/Makefile.dep#L803

In that case, not including the module should be removing `FEATURES_OPTIONAL`.

**Comment by cladmi** [comment]
FEATURES and MODULES are in different concepts. So no `MODULE` should not touch `PERIPH`.

The build system nicely makes all `periph_` features transformed into a dependency to a module of the same name module but it is a really specific case. There are other features that are not transformed directly as modules.

If there should be something to disable optional only features, there should be a dedicated variable 
`FEATURES_OPTIONAL_DISABLE` and it would make sense. Because the `optional` inclusion could be set by something else than the application makefile and you could, because of `FEATURES_CONFLICT` or anything select to not use it.
However, if anything says `FEATURES_REQUIRED` it would still be included.


> I understand that this flag is useful when default modules have to be disabled. But why limit it to default modules? Is there any rational for the actual approach that i don't get here?

The case of `DEFAULT_MODULES` is that they are included even if you put nothing in your application Makefile as they are the common dependencies. But there are cases, usually tests and really edge cases where you basically say "I am disabling an essential part of RIOT and I know what I do".

The solution for not enabling something is to not request its inclusion. If I say "please include networking" with the makefile, and then say, but I would like to not have networking, so will disable it.
You should better not request networking.
We do not really provide ways to patch what is written in your application Makefile.

Also one of the rational for the current documented behavior, depends on the current "implementation".
If you remove an intermediate MODULE, other dependencies may still have already been included and do configuration that required this module to be there.

And currently there are no explicit "optional modules". They are done somehow but not declared that way. It is something I would like to add but I cannot really do before fixing many other things.

**Comment by SemjonKerner** [comment]
Thanks for clearing things up.
So as a conclusion it would make sence to add a `FEATURES_OPTIONAL_DISABLE` flag for that cases and also it could help to add some diversity to `EXPECT_ERRORS`.
