### ISSUE TITLE
gcoap+nanocoap: Missing parameter docs for function pointer types

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#10080]
#### Description

There is no documentation for the function parameters for the handler function pointer types used in nanocoap and gcoap: [coap_handler_t in nanocoap](http://api.riot-os.org/group__net__nanocoap.html#ga687f23858a4a5036b60aedee24fb6b90) and [gcoap_resp_handler_t in gcoap](http://api.riot-os.org/group__net__gcoap.html#ga895178a830f78ae13d4f5c8aa4e329d7)

This should be trivial to add for someone with a good knowledge of nanocoap and gcoap internals, (@kb2ma or @haukepetersen?)

https://github.com/RIOT-OS/RIOT/blob/a6cf9db88003d4f574a700ddbaab650ef9139398/sys/include/net/nanocoap.h#L122-L125

https://github.com/RIOT-OS/RIOT/blob/a6cf9db88003d4f574a700ddbaab650ef9139398/sys/include/net/gcoap.h#L443-L450

My original question is how do I, as an application writer in a CoAP server, use the buf and len parameters in the handler? My current assumption is that buf is a pointer to somewhere in the packet buffer and len is the length of the buffer. How can I be certain that my application will be given enough space to write its response payload?
The CLI example only forwards the buf and len parameters directly to gcoap_resp_init, and then just assumes there is enough space to write RIOT_BOARD at pdu->payload, but this assumption seems like a bad idea in a real world application.

### Useful links

Generated API docs:

- [coap_handler_t in nanocoap](http://api.riot-os.org/group__net__nanocoap.html#ga687f23858a4a5036b60aedee24fb6b90) 
- [gcoap_resp_handler_t in gcoap](http://api.riot-os.org/group__net__gcoap.html#ga895178a830f78ae13d4f5c8aa4e329d7)

**Comment by kb2ma** [comment]
Good question @gebart, and yes more documentation is a good idea. Sorry for the long winded response.

Just to be clear, both nanocoap and gcoap use the same handler type, coap_handler_t, for a server to respond to a request. This is [documented](http://api.riot-os.org/group__net__gcoap.html) in the first sentence of _Creating a response_. For a client, gcoap_resp_handler_t is a gcoap-specific handler for client reception of a server response. gcoap runs in its own thread and notifies the client asynchronously, while nanocoap expects the client to react synchronously when nanocoap_request() or nanocoap_get() return.

Also, #10036 provides much needed module level documentation for nanocoap. Please review that if you haven't seen it.

So, let me document coap_handler_t, and eventually we can add it to the source file.

```
/**
 * @brief   Resource handler type
 * 
 * param[in]  pkt      CoAP PDU data for request
 * param[out] buf      buffer on which to write the response
 * param[out] len      length of buf
 * param[in] context   context provided by resource
 */
typedef ssize_t (*coap_handler_t)(coap_pkt_t *pkt, uint8_t *buf, size_t len, void *context);
```

This should explain the basic nature of buf and len. As a practical matter, buf also is the buffer used for reading the request as well. This dual use is not a requirement, but both gcoap and nanocoap use buf this way. This is pointed out in the module documentation both for gcoap and nanocoap. gcoap and nanocoap write the response differently, so I'll describe them one at a time below.

gcoap reuses pkt to store data as it builds the response. In particular gcoap_resp_init() updates the `payload` and `payload_len` attributes. These attributes also are updated if you add an option via the coap_opt_add_xxx() functions. So,the use model is that an application handler uses these attributes to know where to write the payload and how much space is available. The application handler also must report the length of the payload they wrote in gcoap_finish().

Yes, you are correct that _riot_board_handler() in the gcoap CLI example is sloppy about the payload length. Certainly as an example this should be fixed. gcoap_finish() also should assert (or maybe return -ENOSPC) if the provided payload length is too great.

Historically, nanocoap has differed from gcoap. It does not use the pkt to store data as it builds the response, only the buffer. In this case, the coap_opt_put_xxx() functions return the number of bytes written. It is up the handler writer to track the length remaining in the buffer. I say "historically" because we recently added coap_pkt_init(), which allows nanocoap also to use the pkt when writing the response, like gcoap. This is part of a drive to unite/reuse APIs between nanocoap and gcoap.

gcoap specifies the size of the response buffer in GCOAP_PDU_BUF_SIZE, and nanocoap accepts the buffer in nanocoap_server(). The CoAP block extension provides a way to split a large payload across packets. Block1 support (for a PUT/POST request) was added in #8788, and Block2 (for a GET response) is pending in #8932. By the way, I [mentioned](https://github.com/RIOT-OS/RIOT/pull/8932#discussion_r213998892) in the Block2 PR that it would be useful to have a generic function to accept and write payload buffer content so that we can validate the size before writing.
