### ISSUE TITLE
1-wire driver

### ISSUE THREAD

**Issue by danpetry** [RIOT-OS/RIOT#10236]
#### Description

The DS18 temperature sensor driver merged in https://github.com/RIOT-OS/RIOT/pull/10011 depends on the 1-wire protocol. Both are currently implemented in the DS18 driver. The 1-wire driver should be separated from the DS18 driver. 

There were issues achieving the timing (of the order of microseconds) required by the 1-wire driver, using xtimer_usleep (documented in https://github.com/RIOT-OS/RIOT/issues/10073). Therefore, if xtimer is to be used in the 1-wire driver part of the work to handle this issue would be to characterize xtimer on different platforms, with different configuration settings, including xtimer_spin (which would be a better way to achieve these timings). This may involve using a second periph_timer if available as the source of truth, and may involve reconfiguring periph_timer on certain platforms if necessary, to achieve sub microsecond precision. From this work, a regression test run by Murdock would be a good additional outcome.

An alternative way to achieve these timings might be to use board peripherals directly, such as PWM or any other peripheral which may directly provide details of bus timings. The resulting driver would then have a build dependency on a that cpu feature being present.

**Comment by jcarrano** [comment]
I think xtimer should not be used for bit-banging / software emulated drivers. All MCU's will have some sort of Timer and Capture/Compare peripheral, and that is the way to go.

> An alternative way to achieve these timings might be to use board peripherals directly, such as PWM or any other peripheral which may directly provide details of bus timings.

I think that is the solution.

I will note that these Timer/Capture/Compare are _different_ from a RTI, PIT or RTC timer (which is what you would ideally use to implement xtimer-like functionality, that is an OS timer). I mention this because I saw some confusion regarding this topic. ST ad TI call it "general purpose timer", Atmel seems to call them "Timer/Counter".

1. Using xtimer in this applications demands more precision than what is usually needed. Even though the functions in xtimer take values in µs it does not have µs precision.
2. It is not a problem to use one hardware Timer/Capture/Compare. You are using hardware resources anyways (at least one pin for 1-wire)
3. The Timer/Capture/Compare is actually _designed_ for these kind of application. In particular, it can drive a pin automatically, which significantly reduces complexity and requirements on the SW.
4. Although it may seem "nice" to write such a driver in sequential-blocking style, having a thread do blocking sleeps, being descheduled and scheduled again is wasteful and not really necessary.

My main points are:

1. HW should take care of toggling the pin when the time comes.
2. HW should take care of recording the timing for an incoming signal edge ("capture").
3. There is no point in trying to share one of these timers.
4. The timings are so fast that there is no point in trying to sleep between events.

The issue is that we don't have a generic interface to these peripherals. Of course, if one wants to take full advantage of the HW, then such an interface is useless, but we could have something that supported the basic functionality so that more or less generic drivers could be implemented on top.
