### ISSUE TITLE
Documentation standards

### ISSUE THREAD

**Issue by danpetry** [RIOT-OS/RIOT#10778]
#### Description

The maintainer guidelines and RDM0 give some indication of the contents and review criteria for documentation. Do we need a bespoke set of across-the-board documentation standards? This could:

- give the same style ("look and feel") to all documentation
- encourage documentation to be more complete, which would allow readers to read and understand without having to ask questions
- make it easier and quicker to review documentation

Some items that could be specified could be:

- Examples of a few different types of documents and what their scope, contents and target audience should be
- Details of process when documents relate to code (design documents finalised before PR submission? Documents can have expected revisions? etc)
- Hard requirements on completeness before merging, particularly for API documentation
- RIOT-specific terminology (What is a "module"? etc)
- Requirements on spelling, punctuation and grammar

Here's an example from [Django](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/).

#### Related issues:

https://github.com/RIOT-OS/RIOT/issues/8479
https://github.com/RIOT-OS/RIOT/issues/7889

**Comment by miri64** [comment]
> * give the same style ("look and feel") to all documentation

From experience something like this is hard to enforce in a distributed project such as ours. E.g. in Doxygen some prefer markdown style \`some_var\`, some rather prefer Doxygen command style `@c some_var` and sometimes you have to pick one of the two because Doxygen forces you to (e.g. [`@f$`](http://www.doxygen.nl/manual/commands.html#cmdfdollar) and co). Django uses Pythons own documentation framework which eliminates some of those problems.

> * Requirements on spelling, punctuation and grammar

Here the internationality of our community makes things hard: many don't speak English as their first language and others use different dialects of English which they prefer. On the other hand, a minimum standard to allow for comprehensibility is of course required.
