### ISSUE TITLE
Can't Run UDP example in Esp8266 board

### ISSUE THREAD

**Issue by mmaxus35** [RIOT-OS/RIOT#11827]
OS: Ubuntu 16.04
Reason: Missing file.

I tried to run the examples in esp8266 board in [url](https://riot-os.org/api/group__net__sock__udp.html#details)

I use the makefile in example gnrc_networking.
The output as follows :
`In file included from /home/riot/RIOT-master/examples/udp-simple/server.c:2:0:
/home/riot/RIOT-master/sys/include/net/sock/udp.h:441:24: fatal error: sock_types.h: No such file or directory
 #include "sock_types.h"
                        ^
compilation terminated.
/home/riot/RIOT-master/Makefile.base:83: recipe for target '/home/riot/RIOT-master/examples/udp-simple/bin/esp8266-esp-12x/application_udp-simple/server.o' failed
make[1]: *** [/home/riot/RIOT-master/examples/udp-simple/bin/esp8266-esp-12x/application_udp-simple/server.o] Error 1
/home/riot/RIOT-master/examples/udp-simple/../../Makefile.include:478: recipe for target '/home/riot/RIOT-master/examples/udp-simple/bin/esp8266-esp-12x/application_udp-simple.a' failed
make: *** [/home/riot/RIOT-master/examples/udp-simple/bin/esp8266-esp-12x/application_udp-simple.a] Error 2
`
Summary: sock_types.h cannot found but this example is given in offical docs and esp8266 gnrc networking can run without problems.

I couldn't understand why this problem is occured.

@cgundogan @gschorcht

**Comment by gschorcht** [comment]
I suppose you are just missing an include of a module in your `Makefile`. Since `sock_types.h` is located in directory `sys/net/gnrc/sock/include`, you have to use module `gnrc_sock` to have the include path defined correctly. It is defined in 

https://github.com/RIOT-OS/RIOT/blob/6b094a78a943bcbd74d21a7ce83840c1fdcdc0a6/sys/Makefile.include#L8-L9

BTW, the first sentence of the documentation you are refering is: First you need to include a module that implements this API in your application's Makefile. For example the implementation for GNRC is called gnrc_sock_udp :worried:

Please try to compile `tests/gnrc_socket_udp` and refere the `Makefile` of this test to see what you need to have in your `makefile`.
