### ISSUE TITLE
tests/nordic_softdevice fails randomly when doing `flash test`

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/RIOT#12214]
#### Description

The test `tests/nordic_softdevice` is randomly failing when calling 'test' directly after 'flash'.

When I was testing with letting some time between flash and test, I think it did not fail.

#### Steps to reproduce the issue

```
#! /bin/bash -xe

make --no-print-directory -C tests/nordic_softdevice/

for i in {0..10}; do
    make --no-print-directory -C tests/nordic_softdevice/ flash-only test
done
```

#### Expected results

Never fails

#### Actual results

It fails after some executions

[output.txt](https://github.com/RIOT-OS/RIOT/files/3606503/output.txt)

#### Versions

The first commit that introduced it 2e73e7f04

**Comment by aabadie** [comment]
I just had a look at this and can reproduce the problem very reliably. It seems the softdevice needs some time after reset before it gets in a fully ready state.
The test script sends the ifconfig right after the shell is started so this doesn't give enough time. 
Adding a 1s delay between getting the prompt and then send `ifconfig` works reliably. I know it's not fixing the root cause of the problem (might need to look into the 6lowpan adaption of the softdevice I guess) but would it be a good enough fix ?

**Comment by aabadie** [comment]
see #12465 for a potential fix.
