### ISSUE TITLE
nucleo-f303k8 no longer work since PR #14892

### ISSUE THREAD

**Issue by hugueslarrive** [RIOT-OS/RIOT#14958]
#### Description

No more application or test works since PR #14892.

I think this is because of `CLOCK_CORECLOCK` now defined to 72MHz in ` boards/common/stm32/include/f1f3/cfg_clock_default.h` but the max frequency is 64MHz when using HSI. Moreover CLOCK_PLL_PREDIV is set to 2 and 
CLOCK_PLL_MUL is set to 16 and 8 / 2 * 16 = 64 so CLOCK_CORECLOCK should be set to 64MHz as previously in periph_conf.h.

**Comment by aabadie** [comment]
Thanks for reporting. I confirm the problem and the analysis of the issue. This is fixed by #14923 where the CLOCK_CORECLOCK value is computed automatically, given the PREDIV et MUL PLL parameters. Since #14923 has been reviewed yet and depends on another PR, I'll provide a quick fix and check if there are no other broken nucleo32 boards.
