### ISSUE TITLE
Wifi Support

### ISSUE THREAD

**Issue by mugekuskon** [RIOT-OS/RIOT#19013]
Hello,

I wanted to ask whether RIOT OS has support for WiFi or not. For instance, can two RIOT nodes communicate via WiFi and UART communication with Wifi module (arduino-uno and esp8266-01) is possible or not ? 

Thanks in advance,
Müge

**Comment by maribu** [comment]
Welcome @mugekuskon to the RIOT community!

RIOT has WiFi drivers for the internal WiFi of the [ESP32](https://api.riot-os.org/group__boards__esp32.html) (and the other ESP32* families) as well as for the interal WiFi of the [ESP8266](https://api.riot-os.org/group__boards__esp8266.html).

There also is a driver for the external WiFi chip [ATWINC15x0](https://api.riot-os.org/group__drivers__atwinc15x0.html).

Regarding the suggested setup of using an ESP8266 for providing WiFi only: It is possible to use it as border router and share its network with other network interface. [SLIP](https://en.wikipedia.org/wiki/Serial_Line_Internet_Protocol) is an open standard [supported by RIOT](https://doc.riot-os.org/group__drivers__slipdev.html) to use a serial interface such as UART as network device. So it would be possible to send IPv6 packets over UART via SLIP to an ESP8266 that would forward them via WiFi.

Note that doing actual networking on the ATmega328P will be really challenging. E.g. WiFi has an MTU 1,500 Byte, the ATmega328P has a total RAM of 2,048 Byte. I would recommend to use something with at the very least of 8 KiB of RAM for networking. I am aware that the setup with WiFi via UART does work with the Arduino libs: But note that they use a really high level interface in which the Arduino UNO is only required to understand very little about networking. This kind of "dumb networking mode" is not support by RIOT. I think @benpicco and @keestux were discussing providing a high level sock API interface for such devices, which may allow outsourcing enough of the networking tasks to make the setup usable.

Btw: You will need https://github.com/RIOT-OS/RIOT/pull/18148 when you want to work with your Arduino UNO and RIOT, as otherwise even trivial stuff will easily exceed the RAM of the ATmega328P.

Note that the ESP8266 is a very capable MCU and outperforms the ATmega328P of your Arduino Uno by orders of magnitude even with only the spare CPU time it has left after doing all the WiFi stuff. So you may just ditch the ATmega328P and end up not missing anything.

Also: You may want to check out [our forum](https://forum.riot-os.org/). IMO it is better suited to asking questions than the issues here, as we use the issues on Github mainly for bug reports and tracking.
