### ISSUE TITLE
Sorry, but the latest reported expected results, are showing exactly the same issue.

### ISSUE THREAD

**Issue by PhBressy-Cortus** [RIOT-OS/RIOT#19298]
Sorry, but the latest reported expected results, are showing exactly the same issue.

During the enumeration of the process, described in Read.me
Latest line before the main ...
...
T7 (prio 3, depth 0): trying to lock rmutex now
main: unlocking recursive mutex
...

- T7 is seen as prio 3, but in the source code, T7 is declared as prio 4 !

I agree on the explanations regarding scheduling behaviour, but there is a mismatch beetween code and test Results.
The registered tests results cannot come from the rmutex source code.

- Because 3 != 4

_Originally posted by @PhBressy-Cortus in https://github.com/RIOT-OS/RIOT/issues/19140#issuecomment-1440021684_

**Comment by maribu** [comment]
Thanks for pointing out the mismatch between the output and the README. The output dump in the README is now dropped, so users should no longer be confused by that. We use python scripts (e.g. `tests/rmutex/tests/01-run.py` in this case) that automatically classify a test application run as passed or failed based on the output. This has the benefit that this will automatically catch issues in the nightly builds (which are also running tests on real hardware) or even on regular PR builds (which are running tests on the `native` board only).

The output dump in the README.md apparently got out of sync with the test application and test script. Since we don't expect users to compare the output by hand anyway, there is little benefit of having the maintain a dump of the output in the README that easily gets out of sync anyway. So, we just dropped it to avoid future confusions.
