### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for RIOT

### ISSUE THREAD

**Issue by wangyuliu** [RIOT-OS/RIOT#20105]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **RIOT** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be moderate, with a moderate amount of code related to the CPU architecture in the project.  Is this assessment accurate?Do you have any opinions on personnel allocation and consumption time？ I look forward to your help and response.

**Comment by Teufelchen1** [comment]
Closing since there isn't a specific issue and RIOT compiles fine for RISC-V, even with varying approached to cpu related integration (e.g. compare the ESP32-C3 integration to the hifive1b). Furthermore you seem to just have copy pasted this same issue into 20+ repositories.

If you have a specific issue with RISC-V that pertains to this repository open a new issue with the exact problem you are having. If you want to chat about RIOT I suggest joining our matrix channel: https://matrix.to/#/#riot-os:matrix.org
