### ISSUE TITLE
documentation: periph interface is unclear

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#2046]
The [documentation](https://github.com/RIOT-OS/RIOT/blob/58fffcb50f0f69b484a0b8c24dae18c70c5bef99/drivers/include/periph/random.h) for the random peripheral interface defines three functions that have to do with the state of the device: `random_init()`, `random_poweron()` and `random_poweroff()`. It is unclear (at least to me) under which circumstances it is safe/required to call `random_init`, `random_poweron` and `random_poweroff`.

Examples:
Is it safe to `init; poweroff; poweron;` or `init; poweroff; init;`?
Is it unsafe to `init; poweron;` (and does `auto_init` call `init`)?

The same goes for all peripheral interfaces with such functions.

**Comment by miri64** [comment]
Is this issue still relevant?

**Comment by OlegHahm** [comment]
@LudwigKnuepfer?

**Comment by PeterKietzmann** [comment]
@LudwigKnuepfer IMO the [peripheral documentation](https://riot-os.org/api/group__drivers__periph.html) has greatly improved the past two years and there are a couple more recent issues asking for further doc enhancements. As this issue seems comparatively outdated I'll close it now. Please reopen if I'm mistaken
