### ISSUE TITLE
RIOT 6LoWPAN to Ethernet Bridge (Border Router) - Example or Documentation

### ISSUE THREAD

**Issue by saurabh984** [RIOT-OS/RIOT#2224]
Is there any implementation / example / documentation to get a border router working? I'd like to use an ethernet module connected via SPI.

Thanks
S

**Comment by LudwigOrtmann** [comment]
@saurabh984 did you by any chance start implementing something?

**Comment by cgundogan** [comment]
FYI: I implemented a very simple mqtt client some months ago with basic functionality and  only QoS leve 0 and 1, if I can remember correctly. I did this on posix/linux not on riot itself, because there was no chance to speak to the outer world (excluding hackish ways). If there is still some interest I could try to port this on riot and, with my extended experience of riot now, I would retouch the software to use the vtimer/msg-api instead of threads

**Comment by LudwigOrtmann** [comment]
@cgundogan I'd highly appreciate it, the question is when you'd have time for it ;)
I guess we could also collaborate if you're interested.

**Comment by OlegHahm** [comment]
:+1:

**Comment by saurabh984** [comment]
@LudwigOrtmann No I'm afraid. Will update if I do get some time.

**Comment by LudwigOrtmann** [comment]
@saurabh984 thanks for the update - @cgundogan and me started working on the implementation of MQTT-SN in the meantime.

**Comment by saurabh984** [comment]
@LudwigOrtmann MQTT-SN is not really needed tbh. You can implement the full MQTT protocol which can talk to the Broker directly without the need for something like the border router running a Gateway. MQTT-SN was designed way before IBM thought that something IPv6 was possible on embedded.

MQTT-SN Flow below. Sample implementation here - https://github.com/ty4tw/MQTT-SN

                 Client              Gateway               Broker
                    |                   |                    |      
       PUBLISH() -->| --- SERCHGW ----> |                    |  
                    | <-- GWINFO  ----- |                    |  
                    | --- CONNECT ----> |                    |  
                    | <--WILLTOPICREQ-- |                    |  
                    | --- WILLTOPIC --> |                    |  
                    | <-- WILLMSGREQ -- |                    |  
                    | --- WILLMSG ----> | ---- CONNECT ----> |(accepted)     
                    | <-- CONNACK ----- | <--- CONNACK ----- |   
                    | --- PUBLISH ----> |                    |  
                    | <-- PUBACK  ----- | (invalid TopicId)  |  
                    | --- REGISTER ---> |                    |  
                    | <-- REGACK  ----- |                    |  
                    | --- PUBLISH ----> | ---- PUBLISH ----> |(accepted)  
                    | <-- PUBACK  ----- | <---- PUBACK ----- |    
                    |                   |                    |    
                    //                  //                   //      
                    |                   |                    |          
     SUBSCRIBE() -->| --- SUBSCRIBE --> | ---- SUBSCRIBE --> |     
     [set Callback] | <-- SUBACK ------ | <--- SUBACK ------ |    
                    |                   |                    |    
                    //                  //                   //    
                    |                   |                    |    
                    | <-- REGISTER ---- | <--- PUBLISH ----- |<-- PUBLISH  
    [exec Callback] | <-- PUBLISH  ---- |                    |  
                    | --- PUBACK   ---> | ---- PUBACK  ----> |--> PUBACK  
                    |                   |                    |

**Comment by LudwigOrtmann** [comment]
Why do you say mqtt-sn not needed? The possibility to have topic ids instead of topic strings appears very attractive to me.

**Comment by LudwigOrtmann** [comment]
As for your comparison - sixlowpan appears to do for ipv6 what mqtt-sn does for mqtt... we have sixlowpan too ;)

**Comment by LudwigOrtmann** [comment]
Oh, and the will is optional .. connection establishment can be drastically reduced.

**Comment by saurabh984** [comment]
Need for Gateway as MQTT-SN can not talk to a Broker directly. Haha I know and I meant having sixlowpan means no need for MQTT-SN except for the constrained resources it uses.

Again we'll need a Gateway Implementation too for MQTT-SN to work. Even IBM don't provide one :disappointed:

**Comment by cgundogan** [comment]
Thats true, we need a gateway to talk to the broker. I can imagine that in the long run we also might implement one to have this ability within RIOT. But for now, we can use mosquitto as it is readily equipped with a mqtt-sn gateway and broker.
http://www.eclipse.org/proposals/technology.mosquitto/

**Comment by saurabh984** [comment]
Sounds good. Didn't realise IBM had released RSMB source. Let me know if I can help @LudwigOrtmann @cgundogan

**Comment by LudwigOrtmann** [comment]
https://github.com/LudwigOrtmann/RIOT/tree/mqtt-sn << @saurabh984 the work is happening here

**Comment by saurabh984** [comment]
:+1:

**Comment by OlegHahm** [comment]
Hey @saurabh984, the border router is ready. You just need some Ethernet hardware.

**Comment by msolters** [comment]
@OlegHahm can you elaborate a little on what you mean by "the border router is ready" when using ethernet hardware?

I am building the border router example https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_border_router on an ATMEL SAMR21 Xplained-Pro, but rather than SLIP I am using the `encx24j600` module and an Ethernet1 Xplained-Pro that is connecting directly to a router dishing out IPV6 by DHCP.

I can't seem to wrap my head around how the IP assignment should work here, nor can I get the border router to communicate or successfully ping any other v6 IPs on the same router.

I think it is worth mentioning as well, that the example fails to build when simply replacing the SLIP module with encx24j600.  I had to actually *add* the encx24j600 module, and still keep SLIP.
