### ISSUE TITLE
is there any plan to support touch screen

### ISSUE THREAD

**Issue by sirtian** [RIOT-OS/RIOT#3231]
hi, I searched keyword "touch screen" in issue list and get nothing, so I want to know that is there any plan to support touch screen?

**Comment by PeterKietzmann** [comment]
IMO there are currently no plans for a touch screen driver. The porting for [La BlueFrog](http://www.la-bluefrog.io/) will progress soon (compare  #3020). @YRaoul wanted to write the display driver. Also we have support for the PCD8544 display (Nokia 3310). But all without touch. Any other opinions on this? Otherwise I tend to close this issue.
