### ISSUE TITLE
doc: periph_timer redefine tim_t

### ISSUE THREAD

**Issue by A-Paul** [RIOT-OS/RIOT#3947]
In https://github.com/RIOT-OS/RIOT/pull/3780 it turned out that `tim_t` could not be used in a general test, because this type may be redefined in a cpu-specific implementation.

It should be documented how this replacement would be implemented correctly, and what has to be taken care off, to not break existing code.

**Comment by miri64** [comment]
@haukepetersen bump?

**Comment by OlegHahm** [comment]
Actually, I don't understand the problem.

**Comment by PeterKietzmann** [comment]
I think @A-Paul refers to [this comment](https://github.com/RIOT-OS/RIOT/pull/3780#r39371758)  and asks for enhancement of the documentation [here](https://github.com/RIOT-OS/RIOT/blob/8a74475e70925db155ee9747d514004f8d2dadd7/drivers/include/periph/timer.h#L37)?

**Comment by A-Paul** [comment]
@PeterKietzmann, your assumption is correct. :-)
To be more precise,I followed this advice: https://github.com/RIOT-OS/RIOT/pull/3780#r39622407.

**Comment by PeterKietzmann** [comment]
And did you see your issue solved somewhere during all the documentation efforts? I didn't look it up...

**Comment by kYc0o** [comment]
A gentle ping for those who are involved here. I saw some PRs regarding this issue, however I don't know if we can mark it as solved.

Can someone confirm the doc still missing?

**Comment by haukepetersen** [comment]
No, I think this issue is still valid to some point. Though I think this is not so much about the specific `tim_t` type, but what is (still) missing is a more coherent documentation about the general peripheral driver concept, specifically on the concept of platform specific types this concept is using. 

So anyone volunteering to write something up? I won't get to this anytime soon...
