### ISSUE TITLE
core: preserve disabled IRQs over context switches

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#4025]
Does anyone have a use case for preserving "globally disabled IRQ" state over context switches?

Currently, some platforms do it, some don't, and AFAIK, this "feature" is needed nowhere. If we would hard enable IRQ's on any user-invoked context switch, we could simplify a lot of the IPC code.

**Comment by haukepetersen** [comment]
Hm, seems to me that it is not very useful. If I disable IRQs somewhere in the code, I do this to prevent context switches, right?

Also on Cortex-M platforms, context switches NEED global IRQs to be enabled to work, otherwise the PendSV interrupt (which is doing the context switch) would never be triggered... So this 'feature' is not possible on these platforms anyhow as I see it

**Comment by kaspar030** [comment]
@haukepetersen Exactly. Current code could be simplified a lot if it could expect that a manually triggered context switch re-enables IRQs, that's why I'm asking.

**Comment by haukepetersen** [comment]
So I don't see anything that speaks against this, and as it simplifies stuff, I am of course for it!

**Comment by kaspar030** [comment]
marked as memo, closing for now.
