### ISSUE TITLE
zep example doesn't build

### ISSUE THREAD

**Issue by brummer-simon** [RIOT-OS/RIOT#4206]
Hi Everybody, 

The HowTo for Zep, reachable under (https://github.com/RIOT-OS/RIOT/wiki/Testing-6LoWPAN-on-Ethernet-based-devices), doesn't compile. The Modules in the HowTo are still prefixed with ng instead of gnrc, if I try to build with USEMODULE += gnrc_zep, the function _zep_init() has an undefined reference to function gnrc_nomac_init().

**Comment by authmillenon** [comment]
The Wiki should be editable by you. So if you notice anything deprecated, please don't hesitate to update it.

**Comment by authmillenon** [comment]
About the nomac stuff: I will look into it.

**Comment by authmillenon** [comment]
Ah, since `netdev2_gnrc` does not use nomac anymore you need to add it too to `USEMODULE`. But for some reason `zep_init` now hangs on initialization :-/.

**Comment by authmillenon** [comment]
Okay… because both `gnrc_sixlowpan_nd` and `gnrc_ndp_host` are included https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L534 is always true and always the ZEP interface (because link-local addresses are always back-translated). This leads to an endless loop of ever growing encapsulation (ZEP-Interface sends RA, puts it into ZEP, sends ZEP packet over IP, IP forwards it to ZEP, ZEP puts it into ZEP, sends ZEP packet over IP, etc.). @OlegHahm it was your idea to exit early in this function. Any idea how to fix that (reversing them will also lead to sending it out over the ZEP, because there is nothing in the neighbor cache yet).

**Comment by authmillenon** [comment]
@brummer-simon this problem is a little bit more complicated. Either you deactivate `gnrc_sixlowpan_nd` (which should work) or you have to test on real hardware.

**Comment by miri64** [comment]
I think ZEP is another thing I have to look at ;-)

**Comment by OlegHahm** [comment]
@miri64, I suppose you're not planning to fix this any more with the upcoming change of ZEP, right?

**Comment by miri64** [comment]
Yep, the plan is to remove `gnrc_zep` as soon #6121 is merged
