### ISSUE TITLE
cpu/lpc2387: weird constructs and bit-rot

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4693]
The lpc2387 port has several problems in current master:
- The i2c driver has its own subdirectory
- Some documentation that should be on the wiki is located in `cpu/lpc2387/doc/lpc2387.doc` (a text file, not MS Word)
- Missing a lot of Doxygen comments
- Magic numbers in several implementation files
- uses `F_CPU` macro
- and so on...

**Comment by miri64** [comment]
Ping?

**Comment by miri64** [comment]
I think @maribu is working on this, right?

**Comment by maribu** [comment]
Yep. But it will require a bunch of PRs to get it back up to standards. :-/

The first two however are ready for review

**Comment by miri64** [comment]
Which PRs are those? It's always good to link issues and PRs ;)

**Comment by miri64** [comment]
Ping @maribu @benpicco?

**Comment by benpicco** [comment]
should be mostly resolved now.

**Comment by maribu** [comment]
Yep. It is indeed getting in a pretty good shape. Once the still open PRs of @benpicco are in, this could be closed.

One final touch would be to check whether the use of thumb is beneficial. It would at least reduce programming time quite a bit due to the lower code size. Depending on how the memory is connected to the CPU, it can even increase performance (in case 16 bit thumb instructions can be fetched in one cycle, but 32 bit ARM instructions take two). But it seems only thumb version 1 is supported, so there might be indeed some trade off :-/

**Comment by miri64** [comment]
> Once the still open PRs of @benpicco are in, this could be closed.

Are they in?

**Comment by benpicco** [comment]
I don't have any more cleanup PRs open for lpc23xx

**Comment by miri64** [comment]
Then let's close this finally!
