### ISSUE TITLE
objdump target broken for some boards

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#5066]
Compare https://github.com/RIOT-OS/RIOT/pull/4887#issuecomment-196537220

**Comment by BytesGalore** [comment]
confirmed.
The `OBJDUMP` variable in the `Makefile.include` seems to be empty when called in the mentioned cases. You can reproduce it by setting an `@echo` before the call [1].
Strange that the test above the call doesn't fire.

Setting `OBJDUMP` manually works as expected (e.g. in `RIOT/tests/unittests`):
`make OBJDUMP=arm-none-eabi-objdump BOARD=msba2 tests-fib`

[1] https://github.com/RIOT-OS/RIOT/blob/master/Makefile.include#L333

**Comment by OlegHahm** [comment]
I don't even understand why it is still working for Cortex-M.

**Comment by hexluthor** [comment]
It works on Cortex-M because `Makefile.include.cortexm_common` pulls-in `Makefile.include.gnu`. I mistakenly assumed that all gnu targets would grab `Makefile.include.gnu`, but that is apparently not the case. My tentative plan is to just set `OBJDUMP` everywhere `OBJCOPY` is set. I wonder if it makes sense to have a makefile that adds default values for any variables the BOARD fails to set, `OBJDUMP ?= $(PREFIX)objdump` being an obvious choice.

**Comment by OlegHahm** [comment]
Ah, yes, sorry, I figured that out after a while. My problem was that I was grepping for `Makefile.include.gnu`, but `gnu` was actually hidden in the `TOOLCHAIN` variable. I came up with #5077 then.
