### ISSUE TITLE
make: buildtest breaks when exporting FEATURES_PROVIDED var

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#5128]
for #5065 (and possibly other improvements in the future), I exported the `FEATURES_PROVIDED` variable, so I can use it in some other Makefiles, e.g. in `Makefile.periph` to be the periph driver selectively.

But this breaks the `make buildtest`, as the `Makefile.buildtest` is doing some magic I don't understand...

So I can we fix this?

**Comment by haukepetersen** [comment]
will not be solved for this release -> let's try the next

**Comment by Kijewski** [comment]
[Makefile.buildtests#L41](https://github.com/RIOT-OS/RIOT/blob/3d9f66e91f07f3a4f6b415d29b37c7cfd0ac71c2/Makefile.buildtests#L41)/[#L254](https://github.com/RIOT-OS/RIOT/blob/3d9f66e91f07f3a4f6b415d29b37c7cfd0ac71c2/Makefile.buildtests#L254) are to blame. Either that or the person wrote wrote these lines. \*pfeif\*

Please try to add line `undefine FEATURES_PROVIDED` before both instances of `FEATURES_PROVIDED := $(FEATURES_PROVIDED_BAK)`. `undefined` only exists since GNU make 3.82 (2010-07-28), so there is a tiny chance that not all systems have this functionality.

**Comment by kYc0o** [comment]
And postponed again...

**Comment by kaspar030** [comment]
*bump*

> Please try to add line undefine FEATURES_PROVIDED before both instances of FEATURES_PROVIDED := $(FEATURES_PROVIDED_BAK). undefined only exists since GNU make 3.82 (2010-07-28), so there is a tiny chance that not all systems have this functionality.

doesn't help.

**Comment by OlegHahm** [comment]
Postponing again?

**Comment by haukepetersen** [comment]
fixed by #7507 and export will be added by #6690, so this issue is obsolete.
