### ISSUE TITLE
GNRC: remove neighbor cache from minimal configuration

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5328]
If I remember correctly, it was not possible to build the gnrc_minimal example without neighbor cache because even for link-local communication over 6LoWPAN NDP is required, while it should work also without.

**Comment by authmillenon** [comment]
That's because the reverse-translation is implemented in [6Lo-ND](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/sixlowpan/nd/gnrc_sixlowpan_nd.c#L196-L211). Maybe a cleaner solution that would be helpful with this solution would be to provide this in a separate module, that anyone (including 6Lo-ND, RPL, and `gnrc_minimal`) can use.

**Comment by OlegHahm** [comment]
Yes, I know, I just realized that there has been no issue for this yet.

**Comment by kYc0o** [comment]
Maybe it can be addressed on the new NDP design? For the next release if possible :)

**Comment by miri64** [comment]
This should have been fixed via the NIB rework. Reopen if you disagree.
