### ISSUE TITLE
msp430: ipv6_hdr unittests fail

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5944]
See https://github.com/RIOT-OS/RIOT/issues/1845#issuecomment-253733950.

I'm not sure how this exactly happening, but I suspect the overflow is handled differently.

Might be good to test this for avr and arm platforms, too.

**Comment by PeterKietzmann** [comment]
We're talking about [this test case](https://github.com/RIOT-OS/RIOT/blob/master/tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c#L249) failing. The problem lies [here](https://github.com/RIOT-OS/RIOT/blob/8a74475e70925db155ee9747d514004f8d2dadd7/sys/include/net/ipv6/hdr.h#L291). On 16 bit platforms the sum `(sum + len + prot_num)` already overflowed whereas on 32 bit platforms `sum` is incremented to force the variable to overflow (does it really overflow in each case?). This leads to a different checksums than [`0x1749` ](https://github.com/RIOT-OS/RIOT/blob/master/tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c#L266) on z1 nodes (et al). A quick fix could be to cast the affected variables to `uint32_t` but I didn't investigate weather this is the right way to go.
