### ISSUE TITLE
How to exit from the code? 

### ISSUE THREAD

**Issue by sinkarharshad** [RIOT-OS/RIOT#6016]
Whenever I run any code, after execution I have to manually enter (control+c or cmd+z) to exit the current execution. I have attached the below snapshots for the better clarity. 
My question is: Is there any way to come out from the program via code? 
Thank you in advance.  
![screen shot 2016-10-29 at 01 17 18](https://cloud.githubusercontent.com/assets/18270841/19825151/1731177c-9d76-11e6-9965-d9e39b7f55e2.png)
![screen shot 2016-10-29 at 01 17 31](https://cloud.githubusercontent.com/assets/18270841/19825153/1b32ceb0-9d76-11e6-8e6e-75a0b8cd9ed7.png)

**Comment by x3ro** [comment]
As far as I know, you can achieve this by including `#include "lpm.h"` and changing the MCU's power mode to powerdown/off using either `lpm_set(LPM_POWERDOWN);` or `lpm_set(LPM_OFF);`. To be honest, I don't know the difference.

In any case, a better place to ask development questions regarding RIOT is on the mailing lists (see the [README](https://github.com/RIOT-OS/RIOT/blob/master/README.md)). If, after discussion, the problem turns out to be e.g. a bug or a missing feature, it can then be taken to the issue tracker. This way we avoid cluttering the issue tracker with questions and make it easier for the kernel developers to focus on pressing issues :)
