### ISSUE TITLE
Label cleanup / re-organization

### ISSUE THREAD

**Issue by x3ro** [RIOT-OS/RIOT#6267]
Since my suggestion was ignored / overlooked on the mailing list (and honestly, I prefer GitHub for such discussion w/ images and stuff) I'm opening an issue here.

I propose adopting a scheme similar to [this one](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63#.4lyg41bbf). Existing labels would be renamed to fall into a number of categories, e.g.:

`arm` -> `Architecture: ARM`
`native` -> `Architecture: native`
[...]
`NEEDS SQUASHING` -> `Status: Needs squashing`
`Ready for CI Build` -> `Status: Ready for CI build`
[...]
`bug` -> `Type: bug`
`Feature Request` -> `Type: Feature request`
[...]

You get the idea :D This would result in a sorted label list (by category) both for labels and I'd be able to search for architecture or status and see a list of e.g. available status. Currently I can only guess what a status label might be called, and reading through 52 labels to see if there's something similar all the time does not seem viable (I tend to forgot such things quickly).

Furthermore, I think that (like almost everything else) labels should be introduced/edited through pull requests. Since there are tools (such as [git-labelmaker](https://github.com/himynameisdave/git-labelmaker)) which can update the labels based on a `json` file in the repository, I'd suggest we use one of those. Running this tool could be automated through Travis/Jenkins/You name it.

**Comment by LudwigKnuepfer** [comment]
I added and applied the label (and removed it) only for illustration purposes.

**Comment by LudwigKnuepfer** [comment]
Initially I liked the idea.

However, looking at https://github.com/himynameisdave/git-labelmaker/issues?q=is%3Aissue+is%3Aclosed I have the impression that it gets more difficult to actually read the labels because every second word in the plaintext is metadata.
Also this type of metadata is kind of redundant as the titles themselves already imply a type.
Tool-wise it does not make a difference if it searches for "Status: Ready for CI Build" or "Ready for CI Build".

All in all I conclude that it would be nice to have metadata for the purpose of browsing issues, but that integration into Github is suboptimal and that we don't gain anything else.

**Comment by LudwigKnuepfer** [comment]
I would like to see what the JSON label file looks like and how it integrates, but that is a separate issue IMHO.

**Comment by x3ro** [comment]
Closing this, since it didn't generate any visible interest. Feel free to bring it up again if you're interested.

**Comment by miri64** [comment]
@danpetry maybe this is something you can pick up?

**Comment by danpetry** [comment]
Hi @miri64 , yep this is something I'm interested in, I have made a note and will re-open when I have time to pay it more attention.

**Comment by danpetry** [comment]
Some examples of good labelling:
https://github.com/ARMmbed/mbed-os/pulls
https://github.com/rtrlib/rtrlib/pulls
https://github.com/rust-lang/rust/pulls
In general prefixes look like a good way to go...

**Comment by miri64** [comment]
See also #9449.

**Comment by miri64** [comment]
ANd #10030
