### ISSUE TITLE
driver for cc1020 (the msb-430 transceiver) is missing

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#658]

**Comment by authmillenon** [comment]
That's more of a Feature Request than a bug ;-)

**Comment by PeterKietzmann** [comment]
I'm inclined to close this issue or 'feature request'. It is super old, I couldn't find information about the original MSB430 because it's website is [not found](http://www.mi.fu-berlin.de/inf/groups/ag-tech/projects/Z_Finished_Projects/ScatterWeb/modules/mod_MSB-430.html) and if I see it correctly, the successor [MSB430H](http://www.mi.fu-berlin.de/inf/groups/ag-tech/projects/ScatterWeb/modules/mod_MSB-430H.html) is equipped with a CC1100.

**Comment by miri64** [comment]
@maribu do you have one of those?

**Comment by kaspar030** [comment]
> @maribu do you have one of those?

@OlegHahm has *many*.

**Comment by maribu** [comment]
I have none of these. If noone else so far complained about the missing driver, there seem not to be much demand.

(I could give the datasheet a look if it is similar enough to the CC1101/CC1100/CC1100e family of transceivers to add support to the `cc110x` driver. But I would not add it before the current PR is merged in any case, as I consider adding features counterproductive for the review process.)

**Comment by maribu** [comment]
My first impression after a brief look in the data sheet is that integration into the `cc110x` driver is not a sensible thing to do. It differes significantly in the interface and configuration register layout from the CC1101. I can give it a second look if there still is reasonable demand for this driver.

**Comment by maribu** [comment]
OK, as nobody has expressed interest in having this driver, I close this issue.

If someone having interest in this driver reads this: Please reopen the issue and drop a line or two.
