### ISSUE TITLE
drivers/periph_common : Question about init.c

### ISSUE THREAD

**Issue by ks156** [RIOT-OS/RIOT#6580]
I don't understand why the SPI devices are initialized at startup by this file : https://github.com/RIOT-OS/RIOT/blob/master/drivers/periph_common/init.c#L28

On many CPU, SPI interfaces are alternate functions. Should these alternate functions automatically configured? From my point of view, no, and SPI must be explicitly initialized by the application and not at CPU startup.

**Comment by haukepetersen** [comment]
The problem is, that SPI devices are potentially shared among many uses (i.e. device drivers). Now calling the init function from every driver would be unnecessary overhead. Also this would lead to some side problems like initializing the mutexes etc.

The pin initialization is also something, that only should be done once in the code (instead of again and again for each driver using the same SPI bus). Now it is correct, that if an SPI bus is not used, its pins (and actually the bus itself) should not be initialized. This is not quite true at the moment, but will be fixed implicitly once we build periph drivers only if they are actually used (-> see #5065)
