### ISSUE TITLE
Arduino Mega2560 + XBee doesn't write flash

### ISSUE THREAD

**Issue by diegolondel** [RIOT-OS/RIOT#6917]
Hi everyone!
I'm new here. I'm working on Arduino Mega2560, and I have a little issue. When I test the example "arduino_hello-world" without the XBee module, it works. But when I try to do the same with the XBee module connected (and the XBee shield), It doesn't work, and this happens: 

```
avrdude -p m2560 -c stk500v2 -P /dev/ttyACM0 -b 115200 -F -D -U flash:w:bin/arduino-mega2560/arduino_hello-world.hex

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: reading input file "bin/arduino-mega2560/arduino_hello-world.hex"
avrdude: input file bin/arduino-mega2560/arduino_hello-world.hex auto detected as Intel Hex
avrdude: writing flash (11192 bytes):

Writing | ############################                       | 56% 1.03savrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout

```
The XBee shield has the switch in USB mode.
Any idea?
Thanks!

**Comment by miri64** [comment]
Hi @diegolondel,

sorry for the long delay. Did you connect the xbee shield via UART0 or UART1? The output usually goes over UART0 so if you also connect the XBee shield to that (which the shield does if you just plug it onto the headers), you get a conflict.

Hope that answers your question. Since this is from half a year ago I think you might have solved it by now, so I'm closing the issue.

PS: issues are often the worst place to ask questions because we don't get notified about them, better ask on the devel or users mailinglists.
