### ISSUE TITLE
ROP attack on RIOT

### ISSUE THREAD

**Issue by alexiss03** [RIOT-OS/RIOT#7052]
Hi! 

I have replicated a `Return-oriented Programming (ROP)` attack in RIOT OS by using `ROPGadget` and by adding a CFLAG `-static -fno-stack-protector` in the Makefile of the application I created. Is it left intentional that the stack protector flag can be overriden? 

Thanks,
Lexi

**Comment by gebart** [comment]
It is intentional that all CFLAGS should be possible to override from the project Makefile,  -fstack-protector and -fno-stack-protector are no special exceptions. If you would like to elaborate some more on this potential attack, could you please send an email to security@riot-os.org with some more information?

**Comment by alexiss03** [comment]
Hi!

I'll send an email for this.

Thanks,
Lexi

**Comment by miri64** [comment]
From what we've read on security@riot-os.org this is a vulnerability in the application, not the operating system, so I'm closing this issue. Re-open if you disagree.

**Comment by kaspar030** [comment]
> this is a vulnerability in the application, not the operating system

Well, Lexi just asked if it is intentional that the stack protector can be disabled at compile time, which I think @gebart answered perfectly.
