### ISSUE TITLE
shell commands do not make use of shell_putc

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#712]
@haukepetersen recently noticed that the implementation of most (if not all) shell commands just use printf or puts for printing instead of using the intended shell internal putc function pointer.

**Comment by kushalsingh007** [comment]
@OlegHahm : Can you name a few of those shell commands so that I could have a look at the issue and get started with it.

**Comment by haukepetersen** [comment]
I absolutely agree with @Kijewski, that we should find a general solution for the problem of redirecting stdio instead of just focusing on the shell. For a mid-term solution: how about we remove the `get_char` and `put_char` parameters from the shell for now (and use `getchar()` and `printf/puts` directly in the shell)? And for the long-term we need to think of a way to generally handle the underlying system calls.

**Comment by kaspar030** [comment]
I agree with @Kijewski too, but not all platforms do actually have file descriptors / working get/putchar implementations.

But I agree that the problem lies with those platforms and shell should just use getchar/putchar.

**Comment by gebart** [comment]
@haukepetersen @kaspar030 the Kinetis platforms contain a basic implementation of the device IO table described at http://neptune.billgatliff.com/newlib.html2 which uses a look up table to redirect different IO operations to the proper device driver function based on the file descriptor. This could be adapted to improve the generic syscall implementation.

**Comment by OlegHahm** [comment]
Seems to be a wontfix then. Anyone disagrees?

**Comment by haukepetersen** [comment]
nope

**Comment by LudwigOrtmann** [comment]
nay
