### ISSUE TITLE
Test driver_enc28j60 not running on mopenmote-cc2538 

### ISSUE THREAD

**Issue by maitysubhasis** [RIOT-OS/RIOT#7458]
After flashing the `tests_driver_enc24j600.bin` I can't execute any command over serial port `/dev/ttyUSB0`.  
In case of provided examples the code runs fine. What may be the reason ?

**Comment by smlng** [comment]
@holasm I guess you'll need to adapt some pin configuration in the [Makefile](https://github.com/RIOT-OS/RIOT/blob/master/tests/driver_encx24j600/Makefile#L34) of that test, because the default config uses GPIOs PA0 for CS and PA1 for INT (interrupt). These map to the UART RX and TX pins, which is used by the shell and as they are overridden (or redirected) to the ethernet shield the serial isn't working anymore.
