### ISSUE TITLE
z1: periph_timer not working

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8033]
While testing #8027 I noticed that the tests did not finish on `z1`. Maybe something worth investigating.

**Comment by PeterKietzmann** [comment]
@x3ro would you give it a try at the Hack'n'ACK tonight?

**Comment by x3ro** [comment]
Sorry, this is exceedingly hard to test on macOS since current versions of the msp430 compiler do not work with RIOT at this point in time, and getting the version installed on Murdock involves patching and building GCC 4.x 😓 I don't recommend trying it on macOS and going directly for Ubuntu. I didn't get around to testing this.

**Comment by PeterKietzmann** [comment]
@miri64 please check #8176.

**Comment by PeterKietzmann** [comment]
#8176 fixed the issue
