### ISSUE TITLE
tests: Unittests don't build

### ISSUE THREAD

**Issue by emmanuelsearch** [RIOT-OS/RIOT#8910]
#### Description
Unittests don't build in current master.
Quick bisect we did with @miri64 points to #8844 as introducing this problem.

#### Steps to reproduce the issue
```
cd tests/unittests
make
```

 or

```
make tests-<module>
```

#### Expected results
It should build.

#### Actual results
It does not build. Sample error:

```
make: *** No rule to make target '/home/vagrant/RIOT/tests/unittests/bin/samr21-xpro/tests-tweetnacl.a', needed by '/home/vagrant/RIOT/tests/unittests/bin/samr21-xpro/tests_unittests.elf'.  Stop.

```

#### Versions
Issue detected on Linux and OS X

**Comment by bergzand** [comment]
Confirmed, I noticed the problem here too

**Comment by cladmi** [comment]
I was writing an issue about it, and know why murdock tests run also still pass.

I have a fix for it that I will PR.

**Comment by emmanuelsearch** [comment]
@cladmi great.

**Comment by cladmi** [comment]
They build if you run `make clean all` instead of just `make clean; make all`, that's why murdock could not detect it.
The BUG is hidden because of this line when calling `make clean all`: https://github.com/RIOT-OS/RIOT/blob/2018.01/Makefile.include#L350

Normally it should have failed with other examples, but because of another bug, (BASELIBS values are added after these lines), there was not problem. I will write a proper issue for the real problems.
