### ISSUE TITLE
Manual calibration of the CC1100

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#9]
Currently the CC1100 transceiver is set to automatic calibration every fourth time when going from either RX or TX to IDLE. While there is no manual calibration performed at channel assignment, the first four packets after switching the channel are likely to get lost.

**Comment by PeterKietzmann** [comment]
@fnack even if you may want to refactor this driver again in cause of the new `netdev`: Is this problem still existent?

**Comment by PeterKietzmann** [comment]
@fnack ping

**Comment by OlegHahm** [comment]
@kaspar030, I guess you haven't changed this in the current version?

**Comment by kaspar030** [comment]
honestly, I don't know. Someone needs to look at the registers. AFAIR, I put most of them back to defaults.

**Comment by authmillenon** [comment]
Did somebody check?

**Comment by authmillenon** [comment]
Ping?

**Comment by OlegHahm** [comment]
Looking at the datasheet I wonder if we autocalibrate at all. `MCSM1` is set to `0x17`, which means `TXOFF_MODE` is `RX` and `RXOFF_MODE` is `FSTXON`. Hence, we never go to `IDLE`, but autocalibration happens only for transitions into and from `IDLE`.

**Comment by miri64** [comment]
Has anyone looked into this again? Is this still an issue?

**Comment by OlegHahm** [comment]
The current cc110x driver is not even working correctly AFAIK.

**Comment by kYc0o** [comment]
Is this being tackled by any PR regarding cc110x?

**Comment by kYc0o** [comment]
What happens with this issue? Can be closed?

**Comment by kYc0o** [comment]
@maribu AFAIR you were working with this transceiver. Can you confirm the issue?

**Comment by maribu** [comment]
I'll have a look into it, as soon as I have some time for it and report back.

**Comment by jia200x** [comment]
Is this still an issue?

@maribu could you find some time to check it?

**Comment by maribu** [comment]
@jia200x: The drivers sets the MCSM0 configuration register to `0x18`, so the FS_AUTOCAL bits (page 82 in the data sheet) are set to `0b01`, which enables automatic calibration for every transition to RX or TX. Thus, theoretically this problem should apply. I did not test this, though.

I'm just now in the middle of a complete rewrite of the driver. (I intend to get it upstream when done.)  This issue would not apply to the new driver because of a different approach on calibration.

Also: I seem to be the only use of this transceiver anyway. So I guess no one would complain about closing all cc110x related issues.
