### ISSUE TITLE
Memory suficient boards for sockets in cooja  simulator

### ISSUE THREAD

**Issue by PedroAlfNeto** [RIOT-OS/RIOT#9128]
#### Description
Does anyone know of a compatible board with both RIOT and Cooja simulator that can run the posix-socket example? I've spent the last few days trying to find a compatible board and failing... Apreciate your time.

#### Versions
Linux Mint 18

**Comment by kYc0o** [comment]
I don't know why you closed it, but unfortunately the port for cooja was unattended since a while. As far as I know, cooja works only for msp430 and needs some glue code to work on RIOT. 

You might try [renode](https://github.com/renode/renode) (supported in RIOT) which may be useful for what are you aiming to do.
