### ISSUE TITLE
gcoap Observe: Notifications terminate unexpectedly

### ISSUE THREAD

**Issue by kb2ma** [RIOT-OS/RIOT#9235]
#### Description
Notifications terminate when re-register with the same message ID.

@miri64 writes:

> Another issue I had with equal tokens for the GET is that when the client (out of buggy behavior) sends a NON GET with observe and the same message ID as before, the registration seemed to be dropped (at least the server doesn't send out new notifications anymore). Does this behavior ring a bell for you @kb2ma?

This report is a follow-on to the fix in PR #9209 and issue #9180.

**Comment by miri64** [comment]
I also have to add, that this is not a general occurrence. I only saw it for multihop and only for <50% of the nodes (but the numbers were significant). I'm running a longterm experiment with your fix tonight (but not with duplicate message IDs). We'll see tomorrow, if it really was the message IDs or if it was something else.

**Comment by miri64** [comment]
Some (preliminary) update after a first look onto my longterm experiment: The duplicate message ID don't seem to be the problem for the lost registration. There was however a second GET (different token this time) before the registration was dropped (and the client was sending one final Content packet). I have started another experiment without the fixes in #9209 (and with my modification to the token manager of the client), so I can confirm or deny that it has to do with that fix or the token handling in general.

**Comment by kb2ma** [comment]
Thanks for the additional information, @waehlisch. I wonder if this issue is related to #8287.

I can think of a few compile-time constants for array sizes in gcoap that can be reduced if that will help for experimentation.

**Comment by miri64** [comment]
No, this is a distinct error, since the registration actually get's dropped / is overwritten for some reason.

I now was able to reproduce the bug locally on native, so we are closer to finding a solution (sadly did not find the time yet to step through it with gdb :(). For this I created [this application](https://github.com/miri64/RIOT_playground/tree/master/gcoap_obs_test) (sorry not much documentation yet). It consists of an [aiocoap client script](https://github.com/miri64/RIOT_playground/blob/master/gcoap_obs_test/cli_observe.py) and a [gcoap server](https://github.com/miri64/RIOT_playground/blob/master/gcoap_obs_test/gcoap_cli.c) offering the observable resource `/test`.

The client sends a GET for the resource `/test` with an OBSERVE option to the supplied host and waits for the response. If no response comes after 2 seconds it sends a new one. If a reply comes it starts waiting for notification. Again, if no notification comes after 2 seconds it sends a new GET. The client can be started with the following command and requires `aiocoap` to be installed for python 3.5 or higher

```sh
python3 cli_observe.py "[<link-local address of server>%<TAP interface or bridge to server>]"
```

(the `[]` are actually required for URI construction, they **don't** mean the argument is optional!)

The server tries to publish it's content for `/test` every second. It prints to stdout if that happens or if an error occurs (including that no observer was found). With the `pause` shell command this process can be stopped until the next GET arrives (simulates lost notifications).

Now, if I start both sub-applications and type `pause` to the server *after* a successful registration, the client gets its response, but the server says at least the next 3 notification rounds, that no observer was found. In this set-up the client keeps sending requests, so the situation fixes itself at some point again, but in our original experiment we did not do that, so the registration was lost "forever".

**Comment by miri64** [comment]
Found it! In the end it was a matter of a gdb session of 2 min xD. Will provide a fix!

**Comment by miri64** [comment]
> Will provide a fix!

See #9253

**Comment by miri64** [comment]
Sadly this issue isn't done yet for GETs with already registered tokens. See #9255.
